apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heartbeat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heartbeat
    spec:
      containers:
        - name: asergeev/heartbeat
          image: heartbeat
          ports:
            - name: http-port
              containerPort: 3001
          volumeMounts:
            - name: bd
              mountPath: /database
      volumes:
        - name: bd
          emptyDir: {}       